config/routes.rb
Info2310::Application.routes.draw do
  resources :micro_posts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  
  root to: 'static_pages#home'

end

app/models/micro_post.rb
class MicroPost < ActiveRecord::Base
  attr_accessible :user_id, :content
  
  belongs_to :user
  
  validates :content, presence: true,
                      length: { minimum: 5, maximum: 140 }
  validates :user_id, presence: true
end

app/controllers/micro_posts_controller.rb
class MicroPostsController < ApplicationController
  before_filter :redirect_unless_authorized, only: [:edit, :update, :destroy]

  # GET /micro_posts
  # GET /micro_posts.json
  def index
    @micro_posts = MicroPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @micro_posts }
    end
  end

  # GET /micro_posts/1
  # GET /micro_posts/1.json
  def show
    @micro_post = MicroPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micro_post }
    end
  end

  # GET /micro_posts/new
  # GET /micro_posts/new.json
  def new
    @micro_post = MicroPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micro_post }
    end
  end

  # GET /micro_posts/1/edit
  def edit
  end

  # POST /micro_posts
  # POST /micro_posts.json
  def create
  @micro_post = current_user.micro_posts.build(params[:micro_post])

    respond_to do |format|
      if @micro_post.save
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully created.' }
        format.json { render json: @micro_post, status: :created, location: @micro_post }
        format.js { render :partial => "micro_posts/show"  }
      else
        format.html { render action: "new" }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
        format.js { render :partial => "micro_posts/errors"  }
      end
    end
end

  # PUT /micro_posts/1
  # PUT /micro_posts/1.json
  def update

    respond_to do |format|
      if @micro_post.update_attributes(params[:micro_post])
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micro_posts/1
  # DELETE /micro_posts/1.json
  def destroy
    @micro_post.destroy

    respond_to do |format|
      format.html { redirect_to micro_posts_url }
      format.json { head :no_content }
	  format.js { render :partial => "micro_posts/destroy"  }
    end
  end
  
  private 
    def redirect_unless_authorized
      @micro_post = MicroPost.find(params[:id])
	  @user= User.find(@micro_post.user_id)
	  if current_user != @user
		flash[:error] = "You are not authorized to edit that MicroPost"
		redirect_to root_path
	  end
    end
end

app/views/micro_posts/_destroy.js.erb
$("micro_post_<%= @micro_post.id %>").fadeOut()

app/views/micro_posts/_errors.js.erb
var errors = $('<div class="alert alert-error"/>');

<% @micro_post.errors.full_messages.each do |error| %>
  errors.append('<p><%= j(error) %></p>');
<% end %>

// Display errors before the form
$('#new_micro_post').prepend(errors);
errors.fadeOut(3000);

app/views/micro_posts/_form.html.erb
<%= form_for(@micro_post, remote: true) do |f| %>
  <% if @micro_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micro_post.errors.count, "error") %> prohibited this micro_post from being saved:</h2>

      <ul>
      <% @micro_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/micro_posts/_micro_post.html.erb
<p id= "micro_post_<%= micro_post.id %>">
  <span class='micro_post_timestamp'>
     <%= micro_post.created_at.strftime("%m/%d %l-%M") %>
   </span> 
   <%= micro_post.content %>
   <% if signed_in? && micro_post.user == current_user %>
	 <%= link_to 'Destroy', 
		micro_post, 
		method: :delete, 
		data: { confirm: 'Are you sure?' },
		remote: true 		
	 %>
   <% end %>
</p>

app/views/micro_posts/_show.js.erb
// Get the HTML for a rendered MicroPost
var html = '<%= j(render(:partial => "micro_post", :object => @micro_post))%>';

// create a JQuery DOM element we can insert (and hide it so we can fade it in)
var element = $(html).hide();

// Add it to the user feed, and then fade it in
$('#user_feed').prepend(element);
element.fadeIn(1000);

// Reset the post input to empty
$('#new_micro_post input[type="text"]').val('');

app/views/micro_posts/edit.html.erb
<h1>Editing micro_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @micro_post %> |
<%= link_to 'Back', micro_posts_path %>

app/views/micro_posts/index.html.erb
<h1>Listing micro_posts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @micro_posts.each do |micro_post| %>
  <tr>
    <td><%= micro_post.user_id %></td>
    <td><%= micro_post.content %></td>
    <td><%= link_to 'Show', micro_post %></td>
    <td><%= link_to 'Edit', edit_micro_post_path(micro_post) %></td>
    <td><%= link_to 'Destroy', micro_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micro post', new_micro_post_path %>

app/views/micro_posts/new.html.erb
<h1>New micro_post</h1>

<%= render 'form' %>

<%= link_to 'Back', micro_posts_path %>

app/views/micro_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @micro_post.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @micro_post.content %>
</p>


<%= link_to 'Edit', edit_micro_post_path(@micro_post) %> |
<%= link_to 'Back', micro_posts_path %>