config/routes.rb
Info2310::Application.routes.draw do
  resources :micro_posts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  
  root to: 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
  
  <small>
    <%= link_to 'Rails Tutorial', 'http://railstutorial.org/' %>
    by Michael Hartl
  </small>
  | 
  <%= link_to "INFO2310", 'http://curails.herokuapp.com' %>

</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "MicroPoster", root_path, class: 'brand' %>

      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', static_pages_help_path %></li>
          <li><%= link_to 'About', static_pages_about_path %></li>
		  <li><%= link_to 'Users', users_path %></li>
		  <% if signed_in? %>
		  <li><%= link_to 'My Profile', user_path(current_user) %></li>
		  <li><%= link_to 'My Account', edit_user_path(current_user) %></li>
		  <li><%= link_to 'Logout', session_path(current_user), method: :delete %></li>
		  <% else %>
		  <li><%= link_to 'Login', new_session_path %></li>
		  <% end %>
        </ul>

      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container"> 
	<% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  
  
    <%= yield %>
    <hr />
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>